### ISSUE TITLE
Add support for detecting fullscreen

### ISSUE THREAD

**Issue by ferjm** [Igalia/wpe-android#1]
* We need to add support for detecting when WPE enters full screen
* Additionally add a exitFullscreen() method.

**Comment by MortimerGoro** [comment]
We are about to land a fullscreen API in libwpe. We can take advantage of it to implement fullscreen on wpe-android

**Comment by zhani** [comment]
- GLib: We have the [WebKitWebView:enter-fullscreen](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-enter-fullscreen) signal, which probably is enough for the part related to user interaction (asking permissions, showing a “fullscreen entered” notifications, and so on), and the [libwpe fullscreen API](https://github.com/WebPlatformForEmbedded/libwpe/pull/86) to determine internally when WebKit wants to display content in full screen and do lower level things and e.g. hide button/title bars or use a specific form of output that
