### ISSUE TITLE
Support x86

### ISSUE THREAD

**Issue by ferjm** [Igalia/wpe-android#12]

**Comment by mariospr** [comment]
@aperezdc @zhani @neodesys I'm tentatively setting high prio to this one because I understand being able to use the x86-based emulator would be a huge boost to productivity, and therefore quite important for development. But please let me know if you disagree, thanks!

**Comment by aperezdc** [comment]
> @aperezdc Patches in cerbero repo branch https://github.com/Igalia/cerbero/tree/aperezdc/x86 are required for this

I'll spend some time today to rebase the branch and prepare a PR, thanks for testing!
