### ISSUE TITLE
The mediaplayer demo doesn't render correctly

### ISSUE THREAD

**Issue by neodesys** [Igalia/wpe-android#151]
The mediaplayer demo doesn't render correctly.
On the carousel, some of the iframes may disappear (in particular when starting playing), they rarely reappear.

The issue seems the be related to the preserve3d CSS flag implementation.

**Comment by neodesys** [comment]
Somehow the visual effect looks a little bit the same as issues with z-buffer precision when rendering 3D planes very closed to one each other.

**Comment by neodesys** [comment]
After doing quite some testing, it appears that in fact the issue also occurs on desktop WebKitGTK and wpe-webkit MiniBrowser when using an EGL-based renderer (Wayland).

On X11 desktop with WebKitGTK it is working well, so it seems pointing towards an issue with the EGL renderer in WebKit itself .

A bug has been filed on WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=249583

**Comment by zhani** [comment]
Fixed by https://github.com/Igalia/wpe-android-cerbero/blob/main/recipes/wpewebkit/0014-TextureMapper-Preserve-3d-layers-don-t-get-flattened.patch.
Upstream patch is still under review but it's already applied to wpe-android 2.46.0.
Link to upstream patch https://github.com/WebKit/WebKit/pull/34862
