### ISSUE TITLE
Compositing/rendering is unstable

### ISSUE THREAD

**Issue by neodesys** [Igalia/wpe-android#156]
The rendering is flickering and some layers of the HTML page may disappear from time to time.
The flickering is worse with heavy WebGL scenes or video playing.

**Comment by neodesys** [comment]
The issue is due to the fact that the wpe-webkit threaded compositor is using the canvas FBO target texture without synchronization. So the canvas visual may be composited BEFORE the canvas rendering has finished.

A bug has been filed in WebKit here: https://bugs.webkit.org/show_bug.cgi?id=250314

**Comment by aperezdc** [comment]
@neodesys This looks like it was a tricky issue to hunt down, well done!

**Comment by neodesys** [comment]
Yes, the fix is shorter than the time to understand the source of the issue :smile: 
We still have the `preserve3d` issue https://github.com/Igalia/wpe-android/issues/151 and then we should have something quite stable as far as the rendering is concerned.
