### ISSUE TITLE
Error: Failed to create shared memory

### ISSUE THREAD

**Issue by ferjm** [Igalia/wpe-android#16]
I see the following in the logcat:

> 03-01 10:39:06.820 18210 18285 D wpe-android: Failed to create shared memory: No such file or directory

Which seems to come from https://webkit-search.igalia.com/webkit/rev/337572eabdef05c71633fa5f879faf9d9e7b4cf2/Source/WebKit/Platform/unix/SharedMemoryUnix.cpp#168
This code is patched by https://github.com/Igalia/cerbero/blob/wpe-android/recipes/wpewebkit/0001-Android-remove-uses-of-shm_open-and-shm_unlink.patch

**Comment by aperezdc** [comment]
As currently we are carrying a patch in Cerbero, it would be good to try and submit it to upstream WebKit.
