### ISSUE TITLE
Injected bundle fails to load

### ISSUE THREAD

**Issue by ferjm** [Igalia/wpe-android#17]
I see the following warning in the logcat.

> wpe-android: ** (WPEWebProcess:18307): WARNING **: 10:39:06.511: Error loading the injected bundle (/home/ferjm/dev/igalia/wpe-android/buil
03-01 10:39:06.511 18307 18358 D wpe-android: d/build/dist/android_arm64/lib/wpe-webkit-1.0/injected-bundle/libWPEInjectedBundle.so): dlopen failed: library "/home/ferjm/dev
03-01 10:39:06.511 18307 18358 D wpe-android: /igalia/wpe-android/build/build/dist/android_arm64/lib/wpe-webkit-1.0/injected-bundle/libWPEInjectedBundle.so" not found

This can be easily fixed by allowing WPEAndroid to set the WEBKIT_INJECTED_BUNDLE_PATH env var, which is currently only available in developer mode. https://webkit-search.igalia.com/webkit/rev/337572eabdef05c71633fa5f879faf9d9e7b4cf2/Source/WebKit/UIProcess/API/glib/WebKitWebContext.cpp#310

**Comment by aperezdc** [comment]
Isn't there some function in the Android user space to find out the installation location for an application? It would be nicer to use something like that to calculate the path to the injected bundle, instead of using an environment variable.

**Comment by zhani** [comment]
Even if calculated path would be used for injected bundle location it would still be easier to apply that via WEBKIT_INJECTED_BUNDLE_PATH env var. InjectedBundle path is decided on compile time and there's no possibility to pass it per app other than via WEBKIT_INJECTED_BUNDLE_PATH (unless wpe is compiled with the app).
