### ISSUE TITLE
Allow setting device scale factor

### ISSUE THREAD

**Issue by ferjm** [Igalia/wpe-android#2]
Right now we are hard-coding on the WebKit side a device scale factor of 2.0 for demo purposes on mobile phones. We should allow setting this from the Android layer instead. This needs to arrange calling the existing `wpe_view_backend_dispatch_set_device_scale_factor()` with a suitable value depending on the physical size of the  screen and its pixel density.

**Comment by zhani** [comment]
WPEView calls wpe_view_backend_dispatch_set_device_scale_factor internally based on scale factor provided by DisplayMetrics.
