### ISSUE TITLE
bootstrap build  failed

### ISSUE THREAD

**Issue by kele86838437** [Igalia/wpe-android#50]
I try to run command
 `python3 ./scripts/bootstrap.py --build --debug`
These is an error in cerbero/recipes/gnustl.recipe. It can not find libunwind.a for ndk23 arm64. I try to remove arm64 in gnustl.recipe:58.  

Skip it, I got another error for icu configure. Said that
```
-----> Contents of /media/code/wpe/wpe-android/build/cerbero/build/logs/android_arm64/icu-configure.log:

Recipe 'icu' failed at the build step 'configure'
Command Error: Running ['sh', '-c', '../configure --prefix /media/code/wpe/wpe-android/build/cerbero/build/dist/linux_x86_64 --libdir /media/code/wpe/wpe-android/build/cerbero/build/dist/linux_x86_64/lib --with-pic  --disable-maintainer-mode  --disable-silent-rules  --disable-gtk-doc  --disable-introspection   --enable-shared --enable-static         --disable-renaming --disable-samples --disable-debug         --disable-layout --disable-extras --disable-tests '] returned 77
```

I test it in x64_ubuntu20.04 with python3.8.

**Comment by kele86838437** [comment]
I found this root cause. When extract ndk23 from zip, the python zipfile.extractall  invoke will dismiss soft link in zip. In this case, some executable links or so files don't work.  @zdobersek

**Comment by aperezdc** [comment]
I have submitted a patch to support unpacking `.zip` files with symlinks (and Unix mode bits) to Cerbero upstream: https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/835 — I have the changes locally and unpacking the NDK 23b package results in the correct file system layout, and makes many things work.

**Comment by aperezdc** [comment]
The patch has landed in Cerbero upstream, and bootstrap builds have been working for a while. We can reopen the issue later if the issue resurfaces.
