### ISSUE TITLE
Refactor rendering backend

### ISSUE THREAD

**Issue by ferjm** [Igalia/wpe-android#8]
Right now a Java Surface is generated, then passed it down to C++ and WPE to render into that, finally rendering that surface as the Activity output. @zdobersek suggests a better approach:

> a better approach is to use gralloc, import the retrieved buffer into EGL, have it backing a framebuffer object, render into that, take that gralloc buffer to the Activity, render it

**Comment by ferjm** [comment]
The current approach is to use https://developer.android.com/ndk/reference/group/a-hardware-buffer

**Comment by aperezdc** [comment]
I am quite sure we are [already using AHardwareBuffer](https://github.com/Igalia/wpe-android/blob/8fb995dceb4b392d8c18cf4392781ffc6d29cb0e/wpe/src/main/cpp/browser/exportedbuffer.h#L9) these days. Closing.
