### ISSUE TITLE
Deploy WPE versions on maven or other repo

### ISSUE THREAD

**Issue by zhani** [Igalia/wpe-android#80]
Infrastructure: Deploy WPE versions on maven or other repo accesible from gradle, ideally both stable and autocompiled nightly versions.

**Comment by jonalmeida** [comment]
I'd like to explore how WPE-Android would work as an alternative browser engine for a project on the side, so a nightly artifact would be great to try out. 

Is there somewhere in the mean time where I could consume a pre-built artifact without needing to build the library from scratch?

**Comment by zhani** [comment]
@jonalmeida Unfortunately we don't have pre-built library yet. It's on the roadmap and will be implemented later this year. 

We have prebuilt boostrap packages at [https://wpewebkit.org/android/bootstrap/2.44.1/](https://wpewebkit.org/android/bootstrap/2.44.1/). Script tools/scripts/bootstrap.py can be used to fetch these packages.

**Comment by zhani** [comment]
Published to Maven Central https://central.sonatype.com/artifact/org.wpewebkit.wpeview/wpeview

**Comment by jonalmeida** [comment]
Thanks, I'll try it out soon. :)
